### ISSUE TITLE
feat : 닉네임 등록

### ISSUE THREAD

**Issue by kimhanui** [GodGaji/GajiQuiz_Backend#6]
### 설명
- 사용자는 닉네임을 정할수있다.

### 체크리스트
- [ ] 특수문자 사용 금지
- [ ] 2~8자, 숫자 사용 가능
- [ ] 대소문자 구분 O
- [ ] 닉네임 중복 불가
- [ ] 엔티티에 닉네임 컬럼 추가
- [ ] 테스트코드

**Comment by riyenas0925** [comment]
로그인 기능은 추후에 구현하기로 결정되었기 때문에 이슈 close
