### ISSUE TITLE
feat : 카카오로그인 후 권한 부여

### ISSUE THREAD

**Issue by kimhanui** [GodGaji/GajiQuiz_Backend#7]
### 설명
사용자가 카카오 로그인을 하면 USER 권한을 부여한다.

### 체크리스트
- [x] 관리자는 ADMIN, 사용자는 USER
- [ ] 테스트코드

**Comment by riyenas0925** [comment]
로그인 기능은 추후에 구현하기로 결정되었기 때문에 이슈 close
